################################################################################
#                                                                              #
#     An alternative firmware for Xiaomi Desk Lamp (Yeelight)                  #
#                                                                              #
#                                                                              #
#      Copyright (C) 2018,2019 Tom Stöveken                                    #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; version 2 of the License.                      #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program; if not, write to the Free Software                  #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA    #
#                                                                              #
################################################################################

language: generic

# define variables
env:
  global:
     - ARDUINO_VERSION_TO_USE=1.8.9
     - BD="esp8266:esp8266:generic:CrystalFreq=26,FlashFreq=40,FlashMode=qio,CpuFrequency=80,FlashSize=1M64,Debug=Disabled,LwIPVariant=OpenSource,led=2,ResetMethod=ck,DebugLevel=None____,FlashErase=all"
  #matrix:
  # Values are derived from boards.txt file (https://github.com/esp8266/Arduino/blob/2.4.1/boards.txt)
  
  # for 2.5.x 
  # - BD="esp8266:esp8266:generic:xtal=80,vt=flash,exception=disabled,ResetMethod=ck,CrystalFreq=26,FlashFreq=40,FlashMode=qio,eesz=1M64,led=2,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200"
  # for 2.4.x
  

# steps to do before the install
before_install:
  # download the Arduino IDE, use HTTPS
  - wget https://downloads.arduino.cc/arduino-$ARDUINO_VERSION_TO_USE-linux64.tar.xz
  # unpack it
  - tar xf arduino-$ARDUINO_VERSION_TO_USE-linux64.tar.xz
  # move the unpacked items to a better location
  - sudo mv arduino-$ARDUINO_VERSION_TO_USE /usr/local/share/arduino
  # add the arduino directory so executables are also considered/searched for in that arduino-subfolder
  - export PATH=$PATH:/usr/local/share/arduino

# perform the installation
install:
  # the ESP8266 toolchain is added to the IDE
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  # install the toolchain with this particular version
  - arduino --install-boards esp8266:esp8266:2.4.1
  # configure the actual board to use
  - "echo BOARD: $BD"
  - arduino --board $BD --save-prefs
  # enable all compilation warnings
  - arduino --pref "compiler.warning_level=all" --save-prefs
  # install the required libraries
  - arduino --install-library "ArduinoJson:6.11.0,WiFiManager:0.14.0,Encoder:1.4.1,OneButton:1.3.0"

# compile the Sketch
script:
  - echo $PWD
  - echo $HOME
  - ls $PWD
  - cd $PWD
  - arduino --verify --board $BD Desk-Lamp-Alternative-Firmware.ino

# notify the compilation result (passed or failed)
notifications:
  email:
    on_success: change
    on_failure: change
