language: generic
env:
  global:
     - ARDUINO_VERSION_TO_USE=1.8.9
  matrix:
    - BD="esp8266:esp8266:generic:xtal=80,vt=flash,exception=disabled,ResetMethod=ck,CrystalFreq=26,FlashFreq=40,FlashMode=qio,eesz=1M64,led=2,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200"
before_install:
  - wget https://downloads.arduino.cc/arduino-$ARDUINO_VERSION_TO_USE-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VERSION_TO_USE-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VERSION_TO_USE /usr/local/share/arduino
  - export PATH=$PATH:/usr/local/share/arduino
install:
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266:2.4.1
  - "echo BOARD: $BD"
  - arduino --board $BD --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --install-library "ArduinoJson:6.11.0,WiFiManager:0.14.0,Encoder:1.4.1,OneButton:1.3.0"
script:
  - echo $PWD
  - echo $HOME
  - ls $PWD
  - cd $PWD
  - arduino --verify --board $BD Desk-Lamp-Alternative-Firmware.ino
notifications:
  email:
    on_success: change
    on_failure: change
